const all = {
  en: {
	maplestory: 'MapleStory',
	design: 'Design',
	understand: 'I understand',
	isCashFilter: 'Is Cash',
	genderFilter: 'Gender Filter',
	male: 'Male',
	female: 'Female',
	quickView: 'Quick View',
	removeAll: 'Remove All',
	prototype: 'This project is actively being developed and considered a prototype.',
	alpha: 'Public Alpha',
	unofficialNotice: 'The unofficial MapleStory simulator and designer.',
	properties: 'Properties',
	expression: 'Facial Expression',
	action: 'Pose / Action',
	skin: 'Skin',
	zoom: 'Zoom',
	universal: 'Universal',
	pet: 'Pet',
	character: 'Character',
	name: 'Name',
	illiumEars: 'Flora Ears',
	highFloraEars: 'High Flora Ears',
	mercEars: 'Mercedes Ears',
	frame: 'Frame',
	animate: 'Animate',
	addBgToGif: 'Add BG to GIF',
	visible: 'Visible',
	flipHorizontal: 'Flip Horizontal',
	footholdSnapping: 'Foothold Snapping',
	lock: 'Lock',
	downloadSpriteSheet: 'Download Spritesheet',
	willDownloadZip: 'Will download a .zip',
	downloadLayeredSpriteSheet: 'Download Layered Spritesheet',
	requiresPDNPlugin: 'Requires PDN Plugin',
	deleteCharacter: 'Delete Character',
	deleteCharacterConfirm: 'Are you sure you wish to delete this character?',
	petType: 'Pet Type',
	deletePet: 'Delete Pet',
	accessory: "Accessory",
	badge: "Badge",
	belt: "Belt",
	earrings: "Earrings",
	emblem: "Emblem",
	faceAccessory: "Face Accessory",
	medal: "Medal",
	eyeDecoration: "Eye Decoration",
	earring: "Earring",
	ring: "Ring",
	pendant: "Pendant",
	pocketItem: "Pocket Item",
	powerSource: "Power Source",
	shoulderAccessory: "Shoulder Accessory",
	totem: "Totem",
	armor: "Armor",
	hat: "Hat",
	cape: "Cape",
	top: "Top",
	glove: "Glove",
	overall: "Overall",
	bottom: "Bottom",
	shield: "Shield",
	shoes: "Shoes",
	testArmor: "Test Armor",
	other: "Other",
	android: "Android",
	dragonEquipment: "Dragon Equipment",
	mechanicalHeart: "Mechanical Heart",
	mechanicEquipment: "Mechanic Equipment",
	petEquipment: "Pet Equipment",
	bits: "Bits",
	shovel: "Shovel",
	pickaxe: "Pickaxe",
	skillEffect: "Skill Effect",
	petUse: "Pet Use",
	oneHandedWeapon: "One-Handed Weapon",
	scepter: "Scepter",
	oneHandedAxe: "One-Handed Axe",
	katara: "Katara",
	cane: "Cane",
	dagger: "Dagger",
	desperado: "Desperado",
	whipBlade: "Whip Blade",
	oneHandedBluntWeapon: "One-Handed Blunt Weapon",
	shiningRod: "Shining Rod",
	soulShooter: "Soul Shooter",
	staff: "Staff",
	oneHandedSword: "One-Handed Sword",
	wand: "Wand",
	testWeapon: "Test Weapon",
	cash: "Cash",
	psyLimiter: "Psy-limiter",
	chain: "Chain",
	gauntlet: "Gauntlet",
	secondaryWeapon: "Secondary Weapon",
	ballast: "Ballast",
	magicMarble: "Magic Marble",
	spellbook: "Spellbook",
	arrowFletching: "Arrow Fletching",
	powderKeg: "Powder Keg",
	farSight: "Far Sight",
	card: "Card",
	ironChain: "Iron Chain",
	bowThimble: "Bow Thimble",
	jewel: "Jewel",
	document: "Document",
	magicArrow: "Magic Arrow",
	charm: "Charm",
	orb: "Orb",
	rosary: "Rosary",
	daggerScabbard: "Dagger Scabbard",
	wristBand: "Wrist Band",
	arrowhead: "Arrowhead",
	jettSCore: "Jett's Core",
	novaSEssence: "Nova's Essence",
	soulRing: "Soul Ring",
	magnum: "Magnum",
	kodachi: "Kodachi",
	whistle: "Whistle",
	jettFists: "Jett Fists",
	mass: "Mass",
	foxMarble: "Fox Marble",
	coreController: "Core Controller",
	charges: "Charges",
	chessPiece: "Chess Piece",
	transmitter: "Transmitter",
	wings: "Wings",
	twoHandedWeapon: "Two-Handed Weapon",
	twoHandedAxe: "Two-Handed Axe",
	bow: "Bow",
	crossbow: "Crossbow",
	dualBowgun: "Dual Bowgun",
	gun: "Gun",
	handCannon: "Hand Cannon",
	knuckle: "Knuckle",
	twoHandedBlunt: "Two-Handed Blunt",
	poleArm: "Pole Arm",
	spear: "Spear",
	twoHandedSword: "Two-Handed Sword",
	claw: "Claw",
	katana: "Katana",
	fan: "Fan",
	lapis: "Lapis",
	lazuli: "Lazuli",
	armCannon: "Arm Cannon",
	character: "Character",
	face: "Face",
	hair: "Hair",
	monster: "Monster",
	crusaderCodex: "Crusader Codex",
	monsterBattle: "Monster Battle",
	mount: "Mount",
	consumable: "Consumable",
	potion: "Potion",
	foodAndDrink: "Food and Drink",
	statusCure: "Status Cure",
	petFood: "Pet Food",
	transformation: "Transformation",
	eXPPotion: "EXP Potion",
	characterModification: "Character Modification",
	timeSaver: "Time Saver",
	equipmentBox: "Equipment Box",
	teleportItem: "Teleport Item",
	eXPBuff: "EXP Buff",
	appearance: "Appearance",
	armorScroll: "Armor Scroll",
	helmet: "Helmet",
	eye: "Eye",
	topwear: "Topwear",
	bottomwear: "Bottomwear",
	gloves: "Gloves",
	belts: "Belts",
	shoulder: "Shoulder",
	equipment: "Equipment",
	pet: "Pet",
	weaponScroll: "Weapon Scroll",
	oneHandedBW: "One-Handed BW",
	twoHandedBW: "Two-Handed BW",
	polearm: "Polearm",
	zero: "Zero",
	specialScroll: "Special Scroll",
	cleanSlateScroll: "Clean Slate Scroll",
	slotCarver: "Slot Carver",
	bonusPotentialScroll: "Bonus Potential Scroll",
	chaosScroll: "Chaos Scroll",
	equipEnhancement: "Equip Enhancement",
	potentialScroll: "Potential Scroll",
	awakeningStamp: "Awakening Stamp",
	innocenceScroll: "Innocence Scroll",
	fusionAnvil: "Fusion Anvil",
	whiteScroll: "White Scroll",
	hammer: "Hammer",
	magnifyingGlass: "Magnifying Glass",
	timeExtension: "Time Extension",
	luckyDayScroll: "Lucky Day Scroll",
	protectionScroll: "Protection Scroll",
	safetyScroll: "Safety Scroll",
	guardianScroll: "Guardian Scroll",
	equipmentChange: "Equipment Change",
	soulWeapon: "Soul Weapon",
	miracleCube: "Miracle Cube",
	trade: "Trade",
	masteryBook: "Mastery Book",
	aPSPReset: "AP/SP Reset",
	monsterTaming: "Monster Taming",
	circulator: "Circulator",
	dust: "Dust",
	tablet: "Tablet",
	projectile: "Projectile",
	arrow: "Arrow",
	thrown: "Thrown",
	crossbowBolt: "Crossbow Bolt",
	bullet: "Bullet",
	monsterFamiliar: "Monster/Familiar",
	monsterCard: "Monster Card",
	familiarSkill: "Familiar Skill",
	familiarCard: "Familiar Card",
	recipe: "Recipe",
	smithingRecipe: "Smithing Recipe",
	accessoryCraftingRecipe: "Accessory Crafting Recipe",
	alchemyRecipe: "Alchemy Recipe",
	synergyMachine: "Synergy Machine",
	megaphone: "Megaphone",
	summoningSack: "Summoning Sack",
	message: "Message",
	lieDetector: "Lie Detector",
	wedding: "Wedding",
	owl: "Owl",
	capsule: "Capsule",
	itemPot: "Item Pot",
	monsterDrop: "Monster Drop",
	questItem: "Quest Item",
	cosmetic: "Cosmetic",
	minigame: "Minigame",
	petCommand: "Pet Command",
	book: "Book",
	effect: "Effect",
	coin: "Coin",
	container: "Container",
	eXPTicket: "EXP Ticket",
	eventItem: "Event Item",
	cashShop: "Cash Shop",
	rewardItem: "Reward Item",
	potentialLock: "Potential Lock",
	fusion: "Fusion",
	coupon: "Coupon",
	crafting: "Crafting",
	mineralOre: "Mineral Ore",
	mineralProcessed: "Mineral Processed",
	rareOre: "Rare Ore",
	rareProcessedOre: "Rare Processed Ore",
	craftingItem: "Crafting Item",
	herb: "Herb",
	herbOil: "Herb Oil",
	maker: "Maker",
	chair: "Chair",
	extractor: "Extractor",
	title: "Title",
	decoration: "Decoration",
	key: "Key",
	commerci: "Commerci",
	tradeGood: "Trade Good",
	shipEnhancement: "Ship Enhancement",
	evolutionLab: "Evolution Lab",
	core: "Core",
	mission: "Mission",
	nebulite: "Nebulite",
	rankDNebulite: "Rank D Nebulite",
	rankCNebulite: "Rank C Nebulite",
	rankBNebulite: "Rank B Nebulite",
	rankANebulite: "Rank A Nebulite",
	rankSNebulite: "Rank S Nebulite",
	teleportRock: "Teleport Rock",
	package: "Package",
	itemStore: "Item Store",
	questHelper: "Quest Helper",
	randomReward: "Random Reward",
	specialItem: "Special Item",
	gachapon: "Gachapon",
	surpriseBox: "Surprise Box",
	exchangeCoupon: "Exchange Coupon",
	equipmentModification: "Equipment Modification",
	scroll: "Scroll",
	upgradeSlot: "Upgrade Slot",
	sPAPModification: "SP/AP Modification",
	protection: "Protection",
	eXPCoupon: "EXP Coupon",
	dropCoupon: "Drop Coupon",
	entryPass: "Entry Pass",
	inventorySlot: "Inventory Slot",
	eXPCoupons: "EXP Coupons",
	skillModification: "Skill Modification",
	weapon: "Weapon",
	hairCoupon: "Hair Coupon",
	hairColorCoupon: "Hair Color Coupon",
	faceCoupon: "Face Coupon",
	cosmeticLens: "Cosmetic Lens",
	skinCoupon: "Skin Coupon",
	ear: "Ear",
	facialExpression: "Facial Expression",
	special: "Special",
	petAppearance: "Pet Appearance",
	freeMarket: "Free Market",
	hiredMerchant: "Hired Merchant",
	storePermit: "Store Permit",
	auctionHouse: "Auction House",
	messengerAndSocial: "Messenger and Social",
	weatherEffect: "Weather Effect",
	messenger: "Messenger",
	kite: "Kite",
	note: "Note",
	song: "Song",
	characterEffect: "Character Effect",
	guildForumEmoticon: "Guild Forum Emoticon",
	messageboard: "Messageboard",
	miscellaneous: "Miscellaneous",
	cakeVsPie: "Cake vs Pie",
	language: 'Language',
	playMusic: 'Play Music',
	region: 'Region',
	version: 'Version',
	clone: 'Clone',
	downloadMinimalSpriteSheet: 'Download Minimal Spritesheet',
	downloadMinimalLayeredSpriteSheet: 'Download Minimal Layered Spritesheet',
	export: 'Export',
	importCharacter: 'Import Character'
  },
  kr: {
	ancientBow : "에이션트 보우",
	charactor : "캐릭터",
	maplestory: "메이플스토리", //(space removed)
	design: "디자인",
	understand: "동의합니다", //(edited from 이해 했어)
	isCashFilter: "캐시샵 상품만",
	genderFilter: "성별",
	male: "남성",
	female: "여성",
	quickView: "퀵뷰",
	removeAll: "모두 제거",
	prototype: "이 프로젝트는 활발히 개발되고 있으며 프로토 타입으로 간주됩니다.", //(smoothen out, grammar)
	alpha: "알파 버전",
	unofficialNotice: "비공식 메이플스토리 코디 시뮬레이터.", //(space removed, smoothen)
	properties: "특성",
	expression: "표정",
	action: "자세",
	skin: "피부색",
	zoom: "줌",
	universal: "양성",
	pet: "펫",
	character: "캐릭터",
	name: "이름",
	highFloraEars : "아크 귀",
	illiumEars: "일리움 귀",
	mercEars: "메르세데스 귀",
	frame: "프레임",
	animate: "영상으로 보기",
	addBgToGif: "Add BG to GIF",
	visible: "보이게 하기",
	flipHorizontal: "가로로 뒤집기",
	footholdSnapping: "Foothold Snapping",
	lock: "락",
	downloadSpriteSheet: "스프라이트시트 다운로드",
	willDownloadZip: ".zip 다운로드",
	downloadLayeredSpriteSheet: "레이어드 스프레드시트 다운로드",
	downloadMinimalSpriteSheet: 'Download Minimal Spritesheet',
	requiresPDNPlugin: "PDN 플러그인 필요",
	deleteCharacter: "캐릭터 삭제",
	petType: "펫 종류",
	deletePet: "펫 삭제",
	accessory: "장신구",
	badge: "뱃지",
	belt: "벨트",
	earrings: "귀걸이",
	emblem: "엠블렘",
	faceAccessory: "얼굴장식",
	medal: "훈장",
	eyeDecoration: "눈장식",
	earring: "귀걸이",
	ring: "반지",
	pendant: "펜던트",
	pocketItem: "포켓 아이템",
	powerSource: "하이브리드 하트",
	shoulderAccessory: "견장",
	totem: "토템",
	armor: "방어구",
	hat: "모자",
	cape: "망토",
	top: "상의",
	glove: "장갑",
	overall: "한벌옷",
	bottom: "하의",
	shield: "방패",
	shoes: "신발",
	testArmor: "Test Armor",
	other: "그 외",
	android: "안드로이드",
	dragonEquipment: "드래곤 장비",
	mechanicalHeart: "안드로이드 심장",
	mechanicEquipment: "메카닉 장비",
	petEquipment: "펫 장비",
	bits: "Bits",
	shovel: "삽",
	pickaxe: "곡괭이",
	skillEffect: "스킬 이펙트",
	petUse: "Pet Use",
	oneHandedWeapon: "한손무기",
	scepter: "Scepter", //(not in kr server)
	oneHandedAxe: "한손도끼",
	katara: "카타나",
	cane: "케인",
	dagger: "대거",
	desperado: "데스페라도",
	whipBlade: "에너지 소드",
	oneHandedBluntWeapon: "한손둔기",
	shiningRod: "샤이닝 로드",
	soulShooter: "소울 슈터",
	staff: "스태프",
	oneHandedSword: "한손검",
	wand: "완드",
	testWeapon: "Test Weapon",
	cash: "캐시",
	psyLimiter: "ESP 리미터",
	chain: "체인",
	gauntlet: "건틀렛",
	secondaryWeapon: "보조무기",
	magicMarble: "Magic Marble",
	spellbook: "마도서",
	arrowFletching: "화살깃",
	powderKeg: "화약통",
	farSight: "조준기",
	card: "카드",
	ironChain: "쇠사슬",
	bowThimble: "활골무",
	jewel: "쥬얼리",
	document: "문서",
	magicArrow: "마법화살",
	charm: "매력",
	orb: "오브",
	rosary: "로자리오",
	daggerScabbard: "단검용 검집",
	wristBand: "리스트밴드",
	arrowhead: "화살촉",
	jettSCore: "Jett's Core", //(not in kr server)
	novaSEssence: "용의 정수",
	soulRing: "소울링",
	magnum: "매그넘",
	kodachi: "Kodachi", //(not in kr server)
	whistle: "Whistle", //(not in kr server)
	jettFists: "Jett Fists", //(not in kr server)
	mass: "무게추",
	foxMarble: "여우구슬",
	coreController: "컨트롤러",
	charges: "장약",
	chessPiece: "체스피스",
	transmitter: "무기 전송장치",
	wings: "매직윙",
	twoHandedWeapon: "두손무기",
	twoHandedAxe: "두손도끼",
	bow: "활",
	crossbow: "석궁",
	dualBowgun: "듀얼보우건",
	gun: "건",
	handCannon: "핸드캐논",
	knuckle: "너클",
	twoHandedBlunt: "두손둔기",
	poleArm: "폴암",
	spear: "창",
	twoHandedSword: "두손검",
	claw: "클로",
	katana: "카타나",
	fan: "Fan", //(not in kr server)
	lapis: "태도",
	lazuli: "대검",
	armCannon: "건틀렛 리볼버",
	face: "얼굴",
	hair: "헤어",
	monster: "몬스터",
	crusaderCodex: "Crusader Codex", //(not in kr server) - maybe 인버스 코덱스
	monsterBattle: "배틀 몬스터스 리그",
	mount: "라이딩",
	consumable: "소비",
	potion: "포션",
	foodAndDrink: "음식과 음료",
	statusCure: "상태이상 회복",
	petFood: "펫의 먹이",
	transformation: "Transformation",
	eXPPotion: "경험치 포션",
	characterModification: "Character Modification",
	timeSaver: "Time Saver",
	equipmentBox: "Equipment Box",
	teleportItem: "텔레포트",
	eXPBuff: "경험치 버프",
	appearance: "외형",
	armorScroll: "장비강화 주문서",
	helmet: "헬멧",
	eye: "눈",
	topwear: "상의",
	bottomwear: "하의",
	gloves: "장갑",
	belts: "벨트",
	shoulder: "견장",
	equipment: "장비",
	weaponScroll: "장비강화 주문서",
	oneHandedBW: "한손둔기",
	twoHandedBW: "두손둔기",
	polearm: "폴암",
	zero: "제로",
	specialScroll: "Speical Scroll",
	cleanSlateScroll: "순백의 주문서",
	slotCarver: "각인의 인장",
	bonusPotentialScroll: "고급잠재능력 부여 주문서",
	chaosScroll: "혼돈의 주문서",
	equipEnhancement: "Equip Enhancement",
	potentialScroll: "잠재능력 부여 주문서",
	awakeningStamp: "금빛 각인의 인장",
	innocenceScroll: "이노센트 주문서",
	fusionAnvil: "신비의 모루",
	whiteScroll: "백의 주문서",
	hammer: "망치",
	magnifyingGlass: "감정 돋보기",
	timeExtension: "Time Extension",
	luckyDayScroll: "럭키데이 주문서",
	protectionScroll: "프로텍트 쉴드",
	safetyScroll: "세이프티 쉴드",
	guardianScroll: "리커버리 쉴드",
	equipmentChange: "Equipment Change",
	soulWeapon: "소울웨폰",
	miracleCube: "미라클 큐브",
	trade: "교환",
	masteryBook: "마스터리북",
	aPSPReset: "AP/SP 초기화",
	monsterTaming: "Monster Taming", //(not in kr server)
	circulator: "서큘레이터",
	dust: "더스트",
	tablet: "알약",
	projectile: "투사체",
	arrow: "화살",
	thrown: "Thrown",
	crossbowBolt: "석궁전용 화살",
	bullet: "불릿",
	monsterFamiliar: "Monster/Familiar",
	monsterCard: "Monster Card",
	familiarSkill: "Familiar Skill",
	familiarCard: "Familiar Card",
	recipe: "레시피",
	smithingRecipe: "장비 제작 레시피",
	accessoryCraftingRecipe: "장신구 제작 레시피",
	alchemyRecipe: "연금술 레시피",
	synergyMachine: "Synergy Machine",
	megaphone: "메가폰",
	summoningSack: "의문의 보따리",
	message: "메시지",
	lieDetector: "거짓말 탐지기",
	wedding: "결혼식",
	owl: "부엉이",
	capsule: "캡슐",
	itemPot: "Item Pot",
	monsterDrop: "Monster Drop",
	questItem: "퀘스트 아이템",
	cosmetic: "Cosmetic",
	minigame: "미니게임",
	petCommand: "펫 명령어",
	book: "Book",
	effect: "이펙트",
	coin: "코인",
	container: "Container",
	eXPTicket: "EXP Ticket",
	eventItem: "이벤트 아이템",
	cashShop: "캐시샵",
	rewardItem: "보상 아이템",
	potentialLock: "Potential Lock",
	fusion: "장비 합성",
	coupon: "쿠폰",
	crafting: "제작",
	mineralOre: "Mineral Ore",
	mineralProcessed: "Mineral Processed",
	rareOre: "Rare Ore",
	rareProcessedOre: "Rare Processed Ore",
	craftingItem: "제작 아이템",
	herb: "허브",
	herbOil: "허브 오일",
	maker: "Maker",
	chair: "의자",
	extractor: "Extractor",
	title: "칭호",
	decoration: "Decoration",
	key: "Key",
	commerci: "Commerci",
	tradeGood: "Trade Good",
	shipEnhancement: "Ship Enhancement",
	evolutionLab: "Evolution Lab",
	core: "Core",
	mission: "Mission",
	nebulite: "네뷸라이트",
	rankDNebulite: "D랭크 네뷸라이트",
	rankCNebulite: "C랭크 네뷸라이트",
	rankBNebulite: "B랭크 네뷸라이트",
	rankANebulite: "A랭크 네뷸라이트",
	rankSNebulite: "S랭크 네뷸라이트",
	teleportRock: "순간이동의 돌",
	package: "택배",
	itemStore: "상점",
	questHelper: "Quest Helper",
	randomReward: "랜덤 보상",
	specialItem: "스페셜 아이템",
	gachapon: "Gachapon", //(not in kr server)
	surpriseBox: "Surprise Box",
	exchangeCoupon: "교환 쿠폰",
	equipmentModification: "장비강화",
	scroll: "주문서",
	upgradeSlot: "슬롯 강화",
	sPAPModification: "SP/AP Modification",
	protection: "Protection",
	eXPCoupon: "경험치 쿠폰",
	dropCoupon: "드롭률 쿠폰",
	entryPass: "입장권",
	inventorySlot: "인벤토리 슬롯",
	eXPCoupons: "경험치 쿠폰",
	skillModification: "스킬 강화",
	weapon: "무기",
	hairCoupon: "헤어쿠폰",
	hairColorCoupon: "헤어염색쿠폰",
	faceCoupon: "성형쿠폰",
	cosmeticLens: "카르타의 진주",
	skinCoupon: "스킨케어",
	ear: "귀",
	facialExpression: "표정",
	special: "스페셜",
	petAppearance: "펫 외형",
	freeMarket: "자유시장",
	hiredMerchant: "고용상인",
	storePermit: "개인상점",
	auctionHouse: "경매장",
	messengerAndSocial: "메신저와 소셜",
	weatherEffect: "날씨효과",
	messenger: "메신저",
	kite: "Kite",
	note: "Note",
	song: "노래",
	characterEffect: "캐릭터 이펙트",
	guildForumEmoticon: "길드 포럼 이모티콘",
	messageboard: "게시판",
	miscellaneous: "그 외",
	cakeVsPie: "케이크 vs 파이",
	language: "언어",
	playMusic: "음악 재생",
	region: "지역",
	version: "버전",
	gender: "성별"
  }
}

function fnLang(data){
	return {
		...all['kr'],
		...all[language]
	}
}